// Ten 32px cells across. Rooms form connected cave silhouettes: broad shelves,
// recessed gem pockets and short breakable bridges, with an open descent route.
// # rock, % breakable crate, * gem; d bat, s ghost, h frog, c crawler, m spike.
export const ORBIT_ROOMS=[
  {name:'stepping-stones',rows:[
    '#        #',
    '#  d   h #',
    '#     ####',
    '# s   %%##',
    '#     *  #',
    '# h      #',
    '###   d  #',
    '##%%     #',
    '#   s    #',
    '#        #',
  ]},
  {name:'split-vault',minBand:1,rows:[
    '#        #',
    '# d    s #',
    '##%      #',
    '#*%   %###',
    '###   %**#',
    '##    ####',
    '#   m    #',
    '# h    d #',
    '####%%   #',
    '###      #',
  ]},
  {name:'last-breath',minBand:2,rows:[
    '#        #',
    '# s    d #',
    '#     h  #',
    '#   %%####',
    '#   *  ###',
    '# m      #',
    '#  h   s #',
    '#####    #',
    '###%% d  #',
    '#        #',
  ]},
  {name:'shelves',rows:[
    '#        #',
    '# h   d  #',
    '###      #',
    '###%     #',
    '##       #',
    '#   s  h #',
    '#     ####',
    '# d   %###',
    '#      ###',
    '#        #',
  ]},
  {name:'fork',rows:[
    '#        #',
    '# d      #',
    '#    h   #',
    '#   %%%  #',
    '#   %*%  #',
    '# s %%%  #',
    '#     m  #',
    '# h    d #',
    '####%    #',
    '###      #',
  ]},
  {name:'pocket',rows:[
    '#        #',
    '#  d     #',
    '##    s  #',
    '#*%      #',
    '#*%    h #',
    '###   ####',
    '##   %####',
    '#    s ###',
    '#  d    ##',
    '#        #',
  ]},
  {name:'chute',rows:[
    '#        #',
    '##   d   #',
    '###      #',
    '###    ###',
    '##  s ####',
    '#      ###',
    '#  d    ##',
    '#     h  #',
    '#    %%%##',
    '# s   m ##',
  ]},
  {name:'stairwell',rows:[
    '#        #',
    '# h   d  #',
    '####     #',
    '###%%    #',
    '##   s   #',
    '#      h #',
    '#    %%###',
    '#      ###',
    '#  d    ##',
    '#        #',
  ]},
  {name:'grotto',rows:[
    '#        #',
    '#    d   #',
    '# s   %###',
    '#     %**#',
    '#     %###',
    '# h     ##',
    '####  d  #',
    '###      #',
    '##  s    #',
    '#        #',
  ]},
  {name:'crossfire',minBand:1,rows:[
    '#        #',
    '#  d     #',
    '#      h #',
    '#    %%###',
    '# m     ##',
    '#   s    #',
    '# h    d #',
    '###%%    #',
    '##     m #',
    '#        #',
  ]},
  {name:'fracture',minBand:1,rows:[
    '#        #',
    '#  h   d #',
    '# %%%    #',
    '# %*% s  #',
    '# %%%    #',
    '#     h  #',
    '#    #####',
    '#  d  ####',
    '#      ###',
    '# s      #',
  ]},
];
